### ISSUE TITLE
Switch all prestage enrollments to create standard users

### ISSUE THREAD

**Issue by justatechie** [USS-IT/Jamf-Scripts#19]
Requires we have taken several precautions before we do this:

- [x] ensure remote access via beyond trust is still possible as standard users
- [ ] get most printers that are used by mac users into jamf

**Comment by Zigmoparcheesi** [comment]
Would create users as standard users on their own Macs.
BeyondTrust - PPC already sets most prefs to allow BeyondTrust access. User is only required to perform one step.
Printers: all drivers would need to be loaded into Jamf and printers would need to be entered into Snipe-It with correct IP addresses.
Future version of Jamf will have built-in remote access.

**Comment by justatechie** [comment]
Change has been made to all Prestage Enrollments
