### ISSUE TITLE
Admin rights off for new systems

### ISSUE THREAD

**Issue by justatechie** [USS-IT/Jamf-Scripts#20]

**Comment by Zigmoparcheesi** [comment]
Turns off admin rights for users.

**Comment by justatechie** [comment]
> Turns off admin rights for users.

As of our last Staff Meeting, all newly imaged systems create standard user accounts. Any previous deployed Macs are unaffected by this change.

**Comment by justatechie** [comment]
Change has been made in all Prestage Enrollments
